In [1]:
import pandas as pd
df = pd.read_csv('music_log.csv')
#theory

cholera = pd.read_csv('cholera.csv')
cholera.info()
print(cholera.isnull().sum())
print(cholera.isna().sum())
cholera['imported_cases']=cholera['imported_cases'].fillna(0)
print(cholera.isna().sum())
cholera.dropna(subset=['total_cases','deaths','case_fatality_rate'],inplace=True)
print(cholera)

#practice
new_names = ['user_id',
             'total_play_seconds',
             'artist_name',
             'genre_name',
             'track_name'
             ]
#print(new_names)
df.set_axis(new_names,axis='columns',inplace=True)

#print(df.columns)
#print(df.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   region              23 non-null     object
 1   country             23 non-null     object
 2   total_cases         22 non-null     float64
 3   imported_cases      17 non-null     float64
 4   deaths              22 non-null     float64
 5   case_fatality_rate  22 non-null     float64
 6   notes               2 non-null      object
dtypes: float64(4), object(3)
memory usage: 1.4+ KB
region                 0
country                0
total_cases            1
imported_cases         6
deaths                 1
case_fatality_rate     1
notes                 21
dtype: int64
region                 0
country                0
total_cases            1
imported_cases         6
deaths                 1
case_fatality_rate     1
notes                 21
dtype: int64
region                 0
country                0
total_cases            1
imported_cases         0
deaths                 1
case_fatality_rate     1
notes                 21
dtype: int64
     region                   country  total_cases  imported_cases  deaths  \
0      Азия                Афганистан         33.0             0.0     1.0
1      Азия                     Индия        385.0             0.0     3.0
2      Азия                      Иран        634.0           625.0     4.0
3      Азия                     Йемен    1032481.0             0.0  2261.0
4      Азия                     Китай         14.0             0.0     0.0
5      Азия                     Катар          5.0             5.0     0.0
6      Азия                  Малайзия          2.0             0.0     0.0
7      Азия                     Непал          7.0             0.0     0.0
8      Азия                       ОАЭ         12.0            12.0     0.0
9      Азия         Саудовская Аравия          5.0             5.0     0.0
10     Азия                  Сингапур          3.0             3.0     0.0
11     Азия                   Таиланд          8.0             0.0     0.0
12     Азия                 Филиппины        134.0             0.0     2.0
13     Азия               Южная Корея          5.0             5.0     0.0
14     Азия                    Япония          7.0             5.0     0.0
15  Америка                     Гаити      13681.0             0.0   159.0
16  Америка  Доминиканская Республика        122.0             0.0     4.0
17  Америка                    Канада          4.0             3.0     0.0
18  Америка                       США         11.0             9.0     0.0
19   Африка                Все страны     179835.0             0.0  3220.0
21  Океания                 Австралия          3.0             3.0     0.0
22      Мир                Все страны    1227391.0           675.0  5654.0

    case_fatality_rate                              notes
0                  3.0                                NaN
1                  0.7                                NaN
2                  0.6                                NaN
3                  0.2                                NaN
4                  0.0                                NaN
5                  0.0                                NaN
6                  0.0                                NaN
7                  0.0                                NaN
8                  0.0                                NaN
9                  0.0                                NaN
10                 0.0                                NaN
11                 0.0                                NaN
12                 1.5                                NaN
13                 0.0                                NaN
14                 0.0                                NaN
15                 1.2                                NaN
16                 3.3                                NaN
17                 0.0                                NaN
18                 0.0                                NaN
19                 1.8  нет информации о завозных случаях
21                 0.0                                NaN
22                 0.5                                NaN